---
- name: Install certbot on Rocky Linux 9
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - certbot
    - python3-certbot-dns-ovh
  become: yes

- name: Set the path to letsencrypt
  set_fact:
    letsencrypt_path: "/usr/bin/letsencrypt"
